angular.module('requireUserBug').run [
  '$rootScope'
  '$location'
  ($rootScope, $location) ->
    $rootScope.$on '$stateChangeError', (event, next, previous, error) ->
# We can catch the error thrown when the $requireUser promise is rejected
# and redirect the user back to the main page
      if error == 'AUTH_REQUIRED'
        $location.path '/allow-all'
      return
    return
]
angular.module('requireUserBug').config [
  '$urlRouterProvider'
  '$stateProvider'
  '$locationProvider'
  ($urlRouterProvider, $stateProvider, $locationProvider) ->
    $locationProvider.html5Mode true
    $stateProvider.state('allowAll',
      url: '/allow-all'
      templateUrl: 'client/views/allow-all.ng.html'
      controller: 'MainCtrl'
    ).state 'restrict',
      url: '/restrict'
      templateUrl: 'client/views/restrict.ng.html'
      controller: 'MainCtrl'
      resolve: 'currentUser': [
        '$meteor'
        ($meteor) ->
          $meteor.requireUser()
      ]
    $urlRouterProvider.otherwise '/allow-all'
    return
]

# ---
# generated by js2coffee 2.0.3